language: java
jdk: oraclejdk8
sudo: required

services:
 - docker
  
script: 
 - mvn cobertura:cobertura -B
 - docker build -t scizeron/ipinfo .

after_success:
 - bash <(curl -s https://codecov.io/bash)
 - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
 - docker push ${DOCKER_USERNAME}/ipinfo

deploy:
 
cache:
 directories:
  - $HOME/.m2