language: java
jdk: oraclejdk8
sudo: required

services:
 - docker
  
script: 
 - mvn cobertura:cobertura -B
 - docker build -t scizeron/ipinfo .

after_success:
 - bash <(curl -s https://codecov.io/bash)

deploy:
 
cache:
 directories:
  - $HOME/.m2