language: java
jdk: oraclejdk8
sudo: required

services:
 - docker
  
script: 
 - mvn cobertura:cobertura -B
 - docker build -t scizeron/ipinfo .

after_success:
 - bash <(curl -s https://codecov.io/bash)
 - echo "TEST_VAR:$TEST_VAR"

deploy:
 
cache:
 directories:
  - $HOME/.m2