language: java
jdk: oraclejdk8
sudo: false

install: true
script: 
 - mvn clean package cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
 
cache:
 directories:
  - $HOME/.m2