# ===================================================================
# Logging
# ===================================================================
logging:
 level:
  com.example: DEBUG

management:
 security:
  enabled: false

endpoints:
 hypermedia:
  enabled: true